ci: pin hugo version to 0.139.4 due to special 0.139.5 release
Release 0.139.5 contains no assets and was only made for technical
reasons. The deployment fails with error:

    Error: Action failed with error Unexpected HTTP response: 404

See https://github.com/gohugoio/hugo/issues/13150